# Generated by Django 5.1.2 on 2024-11-26 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease_agreements', '0001_initial'),
        ('rental', '0004_property_status'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseagreement',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='lease_signed',
            field=models.BooleanField(default=False, verbose_name='Lease Signed'),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monthly Rent'),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_agreements', to='rental.property', verbose_name='Property'),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_agreements', to='tenant.tenant', verbose_name='Tenant'),
        ),
    ]
