# Generated by Django 5.1.2 on 2024-10-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaseAgreement',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
