# Generated by Django 5.1.2 on 2024-10-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_delete_leaseagreement_delete_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='monthly_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
