# Generated by Django 5.1.2 on 2024-11-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
